apiVersion: v1
data:
  myvalue: mykey
  secondvalue: secondkey
  thisdkey: thisdvalue
  fourth: four
  fifth: five
  sixth: six
  seventh: seven
  eigth: eight
  ninth: nineeeeeee
  tenth: tenyyyy
kind: ConfigMap
metadata:
  name: forg2

